list1 = [12, 45, 23, 67, 34, 89, 21]
max_num = max(list1)
min_num = min(list1)
sum1 = sum(list1)
avg = sum1/(len(list1))
list1.append(100)
print("Largest number in the list is", max_num)
print("Smallest number in the list is ", min_num)
print("sum of all the numbers are", sum1)
print("average of all the numbers are" , avg)